name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: docker
    env:
      DOTNET_INSTALL_DIR: ~/.local/bin/dotnet

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up .NET
        uses: https://enduringtech.dev/actions/setup-dotnet-action@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: dotnet test --filter Unit.Tests --no-build -c Release --logger "console;verbosity=detailed" --logger trx --collect:"XPlat Code Coverage"

      - name: Upload artifacts
        uses: https://enduringtech.dev/actions/upload-artifact-action@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        if: success() || failure()
        with:
          name: test-results
          path: '**/*.trx'
