name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Docker

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@v4
      - name: Setup .NET
        uses: https://enduringtech.dev/actions/setup-dotnet-action@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: dotnet test --filter Unit.Tests --no-build -c Release --logger "console;verbosity=detailed" --logger trx --collect:"XPlat Code Coverage"

      - name: Upload artifacts
        uses: https://enduringtech.dev/actions/upload-artifact-action@v4
        if: success() || failure()
        with:
          name: test-results
          path: '**/*.trx'
