name: release

on:
  push:
    tags: [ "v*" ]

jobs:
  pack:
    runs-on: docker
    env:
      DOTNET_INSTALL_DIR: ~/.local/bin/dotnet

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up .NET
        uses: https://enduringtech.dev/actions/setup-dotnet-action@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 9.0.x

      - name: Pack
        run: |
          VERSION=${{ github.ref_name }}
          dotnet pack -c Release -o packages /p Version=${VERSION#v}
      - name: Push
        run: |
          dotnet nuget push --skip-duplicate --api-key ${{ secrets.REGISTRY_TOKEN }} --source https://enduringtech.dev/api/packages/interflare/nuget/index.json packages/*
          dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json packages/*

      - name: Upload artifacts
        uses: https://enduringtech.dev/actions/upload-artifact-action@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: packages
          path: packages/*

  release:
    runs-on: docker
    needs: pack

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Download artifacts
        uses: https://enduringtech.dev/actions/download-artifact-action@d8d0a99033603453ad2255e58720b460a0555e1e # v4
        with:
          name: packages
          path: packages

      - name: Generate changelog
        id: changelog
        uses: https://enduringtech.dev/actions/changelog-action@3a3d44d35ba5e531a65472b3bfd89f998225044a # v0.1.0
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create release
        uses: https://enduringtech.dev/actions/release-action@f119011bd6c95ab53d2084ace7b539694ce9b252 # v1.3.2
        with:
          draft: true
          files: packages/*
          body: ${{ steps.changelog.outputs.changes }}

      - name: Commit changelog
        uses: https://enduringtech.dev/actions/commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          branch: main
          commit_message: 'docs: update changelog for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
          commit_user_name: forge[bot]
          commit_user_email: forge.svc@enduringtech.dev
          commit_author: ${{ github.actor }} <${{ github.actor }}@noreply.enduringtech.dev>
