name: release

on:
  push:
    tags: [ "v*" ]

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: pack
        run: |
          VERSION=${{ github.ref_name }}
          dotnet pack -c Release -o packages /p Version=${VERSION#v}
      - name: push
        run: |
          dotnet nuget push --skip-duplicate --api-key ${{ github.token }} --source https://nuget.pkg.github.com/interflare/index.json packages/*
          dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json packages/*

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*

  release:
    runs-on: ubuntu-latest
    needs: pack

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages

      - name: generate changelog
        id: changelog
        uses: requarks/changelog-action@6d71e098526ee17bae963f058d34cd763378337f # v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: create release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          draft: true
          makeLatest: true
          allowUpdates: true
          artifacts: packages/*
          artifactErrorsFailBuild: true
          body: ${{ steps.changelog.outputs.changes }}

      - name: commit changelog
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          branch: main
          commit_message: 'docs: update changelog for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md